package com.example.dell.c1ean.DAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dell.c1ean.Bean.User;
import com.example.dell.c1ean.Bean.Worker;

import com.example.dell.c1ean.DAO.UserDao;
import com.example.dell.c1ean.DAO.WorkerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig workerDaoConfig;

    private final UserDao userDao;
    private final WorkerDao workerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        workerDaoConfig = daoConfigMap.get(WorkerDao.class).clone();
        workerDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        workerDao = new WorkerDao(workerDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Worker.class, workerDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        workerDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public WorkerDao getWorkerDao() {
        return workerDao;
    }

}
