package com.example.dell.c1ean.DAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.dell.c1ean.Bean.CompanyActivity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPANY_ACTIVITY".
*/
public class CompanyActivityDao extends AbstractDao<CompanyActivity, Long> {

    public static final String TABLENAME = "COMPANY_ACTIVITY";

    /**
     * Properties of entity CompanyActivity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
        public final static Property Img = new Property(3, String.class, "img", false, "IMG");
        public final static Property Start_time = new Property(4, String.class, "start_time", false, "START_TIME");
        public final static Property End_time = new Property(5, String.class, "end_time", false, "END_TIME");
        public final static Property Price = new Property(6, float.class, "price", false, "PRICE");
        public final static Property Company_id = new Property(7, long.class, "company_id", false, "COMPANY_ID");
        public final static Property Uses = new Property(8, int.class, "uses", false, "USES");
    }


    public CompanyActivityDao(DaoConfig config) {
        super(config);
    }
    
    public CompanyActivityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPANY_ACTIVITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"TYPE\" TEXT NOT NULL ," + // 2: type
                "\"IMG\" TEXT NOT NULL ," + // 3: img
                "\"START_TIME\" TEXT NOT NULL ," + // 4: start_time
                "\"END_TIME\" TEXT NOT NULL ," + // 5: end_time
                "\"PRICE\" REAL NOT NULL ," + // 6: price
                "\"COMPANY_ID\" INTEGER NOT NULL ," + // 7: company_id
                "\"USES\" INTEGER NOT NULL );"); // 8: uses
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPANY_ACTIVITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CompanyActivity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getType());
        stmt.bindString(4, entity.getImg());
        stmt.bindString(5, entity.getStart_time());
        stmt.bindString(6, entity.getEnd_time());
        stmt.bindDouble(7, entity.getPrice());
        stmt.bindLong(8, entity.getCompany_id());
        stmt.bindLong(9, entity.getUses());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CompanyActivity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getType());
        stmt.bindString(4, entity.getImg());
        stmt.bindString(5, entity.getStart_time());
        stmt.bindString(6, entity.getEnd_time());
        stmt.bindDouble(7, entity.getPrice());
        stmt.bindLong(8, entity.getCompany_id());
        stmt.bindLong(9, entity.getUses());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CompanyActivity readEntity(Cursor cursor, int offset) {
        CompanyActivity entity = new CompanyActivity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2), // type
            cursor.getString(offset + 3), // img
            cursor.getString(offset + 4), // start_time
            cursor.getString(offset + 5), // end_time
            cursor.getFloat(offset + 6), // price
            cursor.getLong(offset + 7), // company_id
            cursor.getInt(offset + 8) // uses
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CompanyActivity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setType(cursor.getString(offset + 2));
        entity.setImg(cursor.getString(offset + 3));
        entity.setStart_time(cursor.getString(offset + 4));
        entity.setEnd_time(cursor.getString(offset + 5));
        entity.setPrice(cursor.getFloat(offset + 6));
        entity.setCompany_id(cursor.getLong(offset + 7));
        entity.setUses(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CompanyActivity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CompanyActivity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CompanyActivity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
