package com.example.dell.c1ean.DAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dell.c1ean.Bean.Company;
import com.example.dell.c1ean.Bean.Order;
import com.example.dell.c1ean.Bean.User;
import com.example.dell.c1ean.Bean.Worker;
import com.example.dell.c1ean.Bean.Wallet;
import com.example.dell.c1ean.Bean.CompanyActivity;
import com.example.dell.c1ean.Bean.OrderPayment;
import com.example.dell.c1ean.Bean.UserInaccount;
import com.example.dell.c1ean.Bean.UserOutaccount;
import com.example.dell.c1ean.Bean.WorkerTimeTable;

import com.example.dell.c1ean.DAO.CompanyDao;
import com.example.dell.c1ean.DAO.OrderDao;
import com.example.dell.c1ean.DAO.UserDao;
import com.example.dell.c1ean.DAO.WorkerDao;
import com.example.dell.c1ean.DAO.WalletDao;
import com.example.dell.c1ean.DAO.CompanyActivityDao;
import com.example.dell.c1ean.DAO.OrderPaymentDao;
import com.example.dell.c1ean.DAO.UserInaccountDao;
import com.example.dell.c1ean.DAO.UserOutaccountDao;
import com.example.dell.c1ean.DAO.WorkerTimeTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig workerDaoConfig;
    private final DaoConfig walletDaoConfig;
    private final DaoConfig companyActivityDaoConfig;
    private final DaoConfig orderPaymentDaoConfig;
    private final DaoConfig userInaccountDaoConfig;
    private final DaoConfig userOutaccountDaoConfig;
    private final DaoConfig workerTimeTableDaoConfig;

    private final CompanyDao companyDao;
    private final OrderDao orderDao;
    private final UserDao userDao;
    private final WorkerDao workerDao;
    private final WalletDao walletDao;
    private final CompanyActivityDao companyActivityDao;
    private final OrderPaymentDao orderPaymentDao;
    private final UserInaccountDao userInaccountDao;
    private final UserOutaccountDao userOutaccountDao;
    private final WorkerTimeTableDao workerTimeTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyDaoConfig = daoConfigMap.get(CompanyDao.class).clone();
        companyDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        workerDaoConfig = daoConfigMap.get(WorkerDao.class).clone();
        workerDaoConfig.initIdentityScope(type);

        walletDaoConfig = daoConfigMap.get(WalletDao.class).clone();
        walletDaoConfig.initIdentityScope(type);

        companyActivityDaoConfig = daoConfigMap.get(CompanyActivityDao.class).clone();
        companyActivityDaoConfig.initIdentityScope(type);

        orderPaymentDaoConfig = daoConfigMap.get(OrderPaymentDao.class).clone();
        orderPaymentDaoConfig.initIdentityScope(type);

        userInaccountDaoConfig = daoConfigMap.get(UserInaccountDao.class).clone();
        userInaccountDaoConfig.initIdentityScope(type);

        userOutaccountDaoConfig = daoConfigMap.get(UserOutaccountDao.class).clone();
        userOutaccountDaoConfig.initIdentityScope(type);

        workerTimeTableDaoConfig = daoConfigMap.get(WorkerTimeTableDao.class).clone();
        workerTimeTableDaoConfig.initIdentityScope(type);

        companyDao = new CompanyDao(companyDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        workerDao = new WorkerDao(workerDaoConfig, this);
        walletDao = new WalletDao(walletDaoConfig, this);
        companyActivityDao = new CompanyActivityDao(companyActivityDaoConfig, this);
        orderPaymentDao = new OrderPaymentDao(orderPaymentDaoConfig, this);
        userInaccountDao = new UserInaccountDao(userInaccountDaoConfig, this);
        userOutaccountDao = new UserOutaccountDao(userOutaccountDaoConfig, this);
        workerTimeTableDao = new WorkerTimeTableDao(workerTimeTableDaoConfig, this);

        registerDao(Company.class, companyDao);
        registerDao(Order.class, orderDao);
        registerDao(User.class, userDao);
        registerDao(Worker.class, workerDao);
        registerDao(Wallet.class, walletDao);
        registerDao(CompanyActivity.class, companyActivityDao);
        registerDao(OrderPayment.class, orderPaymentDao);
        registerDao(UserInaccount.class, userInaccountDao);
        registerDao(UserOutaccount.class, userOutaccountDao);
        registerDao(WorkerTimeTable.class, workerTimeTableDao);
    }
    
    public void clear() {
        companyDaoConfig.clearIdentityScope();
        orderDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        workerDaoConfig.clearIdentityScope();
        walletDaoConfig.clearIdentityScope();
        companyActivityDaoConfig.clearIdentityScope();
        orderPaymentDaoConfig.clearIdentityScope();
        userInaccountDaoConfig.clearIdentityScope();
        userOutaccountDaoConfig.clearIdentityScope();
        workerTimeTableDaoConfig.clearIdentityScope();
    }

    public CompanyDao getCompanyDao() {
        return companyDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public WorkerDao getWorkerDao() {
        return workerDao;
    }

    public WalletDao getWalletDao() {
        return walletDao;
    }

    public CompanyActivityDao getCompanyActivityDao() {
        return companyActivityDao;
    }

    public OrderPaymentDao getOrderPaymentDao() {
        return orderPaymentDao;
    }

    public UserInaccountDao getUserInaccountDao() {
        return userInaccountDao;
    }

    public UserOutaccountDao getUserOutaccountDao() {
        return userOutaccountDao;
    }

    public WorkerTimeTableDao getWorkerTimeTableDao() {
        return workerTimeTableDao;
    }

}
